const employeeData = [
  {
    id: 1,
    fullName: "Lana Winters",
    age: 38,
    dob: "1985-05-15",
    salary: 80000,
    designation: "Journalist",
    image: "../images/lanawinters.png",
    department: "Inmate",
  },
  {
    id: 2,
    fullName: "Sister Mary Eunice",
    age: 29,
    dob: "1994-02-10",
    salary: 75000,
    designation: "Briarcliff Staff",
    image: "../images/sistereunice.png",
    department: "Briarcliff",
  },
  {
    id: 3,
    fullName: "Oliver Thredson",
    age: 47,
    dob: "1976-02-10",
    salary: 135000,
    designation: "Psychiatrist",
    image: "../images/drthredson.png",
    department: "Briarcliff",
  },
  {
    id: 4,
    fullName: "Kit Walker",
    age: 24,
    dob: "1999-02-10",
    salary: 79000,
    designation: "Filling Station Owner",
    image: "../images/kitwalker.png",
    department: "Inmate",
  },
  {
    id: 5,
    fullName: "Mrs Reynolds",
    age: 50,
    dob: "1973-02-10",
    salary: 18000,
    designation: "Housewife",
    image: "../images/mrsreynolds.png",
    department: "Inmate",
  },
  {
    id: 6,
    fullName: "Frank McCann",
    age: 48,
    dob: "1975-02-10",
    salary: 22000,
    designation: "Security Guard",
    image: "../images/frankmccann.png",
    department: "Briarcliff",
  },
  {
    id: 7,
    fullName: "Leigh Emerson",
    age: 62,
    dob: "1961-02-10",
    salary: 35100,
    designation: "Serial Killer",
    image: "../images/leighemerson.png",
    department: "Inmate",
  },
  {
    id: 8,
    fullName: "Grace Bertrand",
    age: 26,
    dob: "1997-02-10",
    salary: 18000,
    designation: "Housewife",
    image: "../images/gracebertrand.png",
    department: "Inmate",
  },
  {
    id: 9,
    fullName: "Arthur Arden",
    age: 63,
    dob: "1960-02-10",
    salary: 60000,
    designation: "Physician",
    image: "../images/arthurarden.png",
    department: "Briarcliff",
  },
  {
    id: 10,
    fullName: "Mother Claudia",
    age: 59,
    dob: "1964-02-10",
    salary: 33120,
    designation: "Mother Superior",
    image: "../images/motherclaudia.png",
    department: "Briarcliff",
  },
];

export default employeeData;
